services:
  backend:
    image: tanujachennurkar/investmentplanner-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: tanujachennurkar/investmentplanner-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5172:5172"
    depends_on:
      - backend
